development:
  itinerary_path: public/#{@itin_preview.document_file_name}

production:
  itinerary_path: https://s3-us-west-2.amazonaws.com/travelforwardapp/itineraries/documents/000/000/008/original/portugal_itinerary.pdf
